#!/bin/sh -x

### This is the version that uses a JAR file.

# Archive the chrome packages.
# \*/.\* excludes hidden Unix files (i.e. those that start with a period).
# To avoid shipping locales that aren't being used, we only include locales
# that have entries in chrome.manifest.
cd chrome
zip -9 -ur personas.jar content skin -x \*/.\*
zip -9 -ur personas.jar `awk '/^locale / { print "locale/" $3 }' ../chrome.manifest` -x \*/.\*
cd ..

# Back up the chrome.manifest file so we can restore it to its pristine state
# after we finish building the XPI with the version of chrome.manifest that has
# been modified to point to the archive versions of the chrome packages.
cp chrome.manifest .\#chrome.manifest.bak

# Convert the chrome provider instructions in the chrome.manifest file
# to point to the archived versions of the chrome packages.
sed -i -r -e 's/^((content|skin|locale)\s+(\S+\s+)(\S+\s+)?)chrome\//\1jar:chrome\/personas.jar!\//g' chrome.manifest

# Build the XPI.
zip -9 -ur personas.xpi chrome/personas.jar modules defaults install.rdf chrome.manifest -x \*/.\*

# Restore the backed up chrome.manifest file.
mv .\#chrome.manifest.bak chrome.manifest

### End of the version that uses a JAR file.


### This is the version that doesn't use a JAR file.

# Build the XPI.
# \*/.\* excludes hidden Unix files (i.e. those that start with a period).
# To avoid shipping locales that aren't being used, we only include locales
# that have entries in chrome.manifest.
#zip -9 -ur personas.xpi chrome/content chrome/skin modules defaults install.rdf chrome.manifest -x \*/.\*
#zip -9 -ur personas.xpi `awk '/^locale / { print $4 }' chrome.manifest` -x \*/.\*

### End of the version that doesn't use a JAR file.
