#!/bin/sh -x

# Archive the chrome packages.
# We're not using it now because it's not clear why it matters.
#cd chrome
# \*/.\* excludes all hidden Unix files (i.e. those that start with a period)
#zip -9 -ur personas.jar content locale skin -x \*/.\*
#cd ..

# Back up the chrome.manifest file so we can restore it to its pristine state
# after we finish building the XPI with the version of chrome.manifest that has
# been modified to point to the archive versions of the chrome packages.
cp chrome.manifest .\#chrome.manifest.bak


### This is the version that uses a JAR file.
# We're not using it now because it's not clear why it matters.

# Convert the chrome provider instructions in the chrome.manifest file
# to point to the archived versions of the chrome packages.
#sed -i -r -e 's/^((content|skin|locale)\s+(\S+\s+)(\S+\s+)?)chrome\//\1jar:chrome\/personas.jar!\//g' chrome.manifest

# Build the XPI.
#zip -9 -ur personas.xpi chrome/personas.jar modules defaults install.rdf chrome.manifest -x \*/.\*

### End of the version that uses a JAR file.


### This is the version that doesn't use a JAR file.
# We're using this at the moment because it's simpler.

# Build the XPI.
zip -9 -ur personas.xpi chrome/content chrome/skin chrome/locale modules defaults install.rdf chrome.manifest -x \*/.\*

### End of the version that doesn't use a JAR file.


# Restore the backed up chrome.manifest file.
mv .\#chrome.manifest.bak chrome.manifest
