#!/bin/sh -x

# Compile the IDL files into XPT files.
cd components
./xptgen
cd -

# Archive the chrome packages.
cd chrome
# \*/CVS/\* excludes all files in CVS directories
# \*/.\* excludes all hidden Unix files (i.e. those that start with a period)
zip -9 -ur personas.jar content locale skin -x \*/CVS/\* -x \*/.\*
cd ..

# Back up the chrome.manifest file so we can restore it to its pristine state
# after we finish building the XPI with the version of chrome.manifest that has
# been modified to point to the archive versions of the chrome packages.
cp chrome.manifest .\#chrome.manifest.bak

# Convert the chrome provider instructions in the chrome.manifest file
# to point to the archived versions of the chrome packages.
sed -i -r -e 's/^((content|skin|locale)\s+(\S+\s+)(\S+\s+)?)chrome\//\1jar:chrome\/personas.jar!\//g' chrome.manifest

# Build the XPI.
# components/\*.idl excludes IDL files, which are unnecessary in the XPI
#                   since the info in them has been compiled into XPT files
# components/xptgen excludes that script, which is part of the build process
zip -9 -ur personas.xpi chrome/personas.jar components defaults install.rdf chrome.manifest -x \*/CVS/\* -x \*/.\* -x components/\*.idl -x components/xptgen

# Restore the backed up chrome.manifest file.
mv .\#chrome.manifest.bak chrome.manifest
