#!/bin/sh -x

if [[ ! -d $MOZSDKDIR ]]; then
    echo "MOZSDKDIR environment variable must point to a XULRunner SDK directory"
    exit 1
fi

for idl in `find . -type f -name \*.idl`; do
    $MOZSDKDIR/bin/xpidl -m typelib -I $MOZSDKDIR/idl $idl
done
